[tool.poetry]
name = "ai-service"
version = "0.1.0"
packages = [
  { include = "src" }
]

[tool.poetry.dependencies]
python = "^3.10"
langchain
huggingface_hub
langchain_community
langchain-text-splitters
faiss-cpu
langchain-huggingface
langchain-openai
pypdf
numpy==1.26.2
langsmith
openai
python-dotenv = "^1.1.0"
core-backend = { path = "../../packages/core-backend", develop = true }
